#ifndef _AVR_ATMEGA328PB_VIVIWARE_H_INCLUDED
#define _AVR_ATMEGA328PB_VIVIWARE_H_INCLUDED

#define BOARD_TYPE_BRANCH            (0)
#define BOARD_TYPE_DEPRECATED_CUSTOM (1)
#define BOARD_TYPE_USER_BRANCH       (2)
#define BOARD_TYPE_CUSTOM            (3)

#endif   /* #ifdef _AVR_ATMEGA328PB_VIVIWARE_H_INCLUDED */
